# params.yaml - Project B: Traffic Light Behaviour

traffic_light_detector:
  ros__parameters:
    image_topic: /oak/rgb/image_raw
    output_topic: /traffic_light_state
    show_debug: false
    roi_top_fraction: 0.75
    min_blob_area: 90.0
    max_blob_area_fraction: 0.08
    min_circularity: 0.45
    min_confidence: 0.45
    stable_frames: 3
    unknown_timeout_sec: 0.8

traffic_light_controller:
  ros__parameters:
    state_topic: /traffic_light_state
    cmd_vel_topic: /cmd_vel
    cmd_vel_stamped: true
    cmd_vel_frame_id: base_link
    green_speed: 0.18
    yellow_speed: 0.06
    state_timeout_sec: 1.0
