"""Launch Project C with Nav2 Collision Monitor as the final safety layer."""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    pkg = FindPackageShare('rosbot_obstacle_avoidance')
    project_c_launch = PathJoinSubstitution([pkg, 'launch', 'project_c.launch.py'])
    collision_config = PathJoinSubstitution(
        [pkg, 'config', 'collision_monitor_params.yaml']
    )

    args = [
        DeclareLaunchArgument('scan_topic', default_value='/scan_filtered'),
        DeclareLaunchArgument('depth_topic', default_value='/camera/depth/image_rect_raw'),
        DeclareLaunchArgument('pointcloud_topic', default_value='/oak/points'),
        DeclareLaunchArgument('pointcloud_frame', default_value='optical'),
        DeclareLaunchArgument('pointcloud_target_frame', default_value='base_link'),
        DeclareLaunchArgument('pointcloud_use_tf', default_value='true'),
        DeclareLaunchArgument('pointcloud_tf_timeout_sec', default_value='0.03'),
        DeclareLaunchArgument('pointcloud_qos', default_value='sensor_data'),
        DeclareLaunchArgument('tof_topic', default_value='/range'),
        DeclareLaunchArgument(
            'tof_topics',
            default_value='/range/fl,/range/fr,/range/rl,/range/rr',
        ),
        DeclareLaunchArgument('use_lidar', default_value='true'),
        DeclareLaunchArgument('use_depth', default_value='false'),
        DeclareLaunchArgument('use_pointcloud', default_value='true'),
        DeclareLaunchArgument('use_tof', default_value='true'),
        DeclareLaunchArgument('front_center_angle_deg', default_value='180.0'),
        DeclareLaunchArgument('front_path_half_width_m', default_value='0.16'),
        DeclareLaunchArgument('cmd_vel_topic', default_value='/cmd_vel'),
        DeclareLaunchArgument('cmd_vel_raw_topic', default_value='/cmd_vel_raw'),
        DeclareLaunchArgument('cmd_vel_stamped', default_value='true'),
        DeclareLaunchArgument('odom_topic', default_value='/odom'),
        DeclareLaunchArgument('imu_topic', default_value='/imu'),
        DeclareLaunchArgument('front_tof_topics', default_value='/range/fl,/range/fr'),
        DeclareLaunchArgument('max_speed', default_value='0.085'),
        DeclareLaunchArgument('stop_distance', default_value='0.25'),
        DeclareLaunchArgument('hard_backup_distance', default_value='0.10'),
        DeclareLaunchArgument('front_tof_obstacle_distance', default_value='0.30'),
        DeclareLaunchArgument('front_tof_hard_distance', default_value='0.12'),
        DeclareLaunchArgument('dodge_clearance', default_value='0.03'),
        DeclareLaunchArgument('dodge_forward_speed', default_value='0.045'),
        DeclareLaunchArgument('dodge_angular_speed', default_value='0.45'),
        DeclareLaunchArgument('rotation_angular_speed', default_value='0.50'),
        DeclareLaunchArgument('dodge_step_deg', default_value='60.0'),
        DeclareLaunchArgument('dodge_pivot_sec', default_value='0.60'),
        DeclareLaunchArgument('front_release_distance', default_value='0.45'),
        DeclareLaunchArgument('front_clear_exit_frames', default_value='5'),
        DeclareLaunchArgument('creep_speed', default_value='0.04'),
        DeclareLaunchArgument('clearer_side_deadband', default_value='0.05'),
        DeclareLaunchArgument('avoid_turn_direction', default_value='-1.0'),
        DeclareLaunchArgument('side_guard_distance', default_value='0.03'),
        DeclareLaunchArgument('side_escape_distance', default_value='0.05'),
        DeclareLaunchArgument('side_escape_angular_speed', default_value='0.30'),
        DeclareLaunchArgument('edge_escape_enabled', default_value='true'),
        DeclareLaunchArgument('edge_escape_front_distance', default_value='0.15'),
        DeclareLaunchArgument('edge_escape_clearance', default_value='0.30'),
        DeclareLaunchArgument('edge_escape_angular_speed', default_value='0.45'),
        DeclareLaunchArgument('edge_escape_sec', default_value='0.80'),
        DeclareLaunchArgument('edge_escape_max_attempts', default_value='3'),
        DeclareLaunchArgument('backup_speed', default_value='0.06'),
        DeclareLaunchArgument('battery_topic', default_value='/battery'),
        DeclareLaunchArgument('require_battery_ok', default_value='false'),
        DeclareLaunchArgument('min_battery_voltage', default_value='11.1'),
        DeclareLaunchArgument('warn_battery_voltage', default_value='11.4'),
        DeclareLaunchArgument('battery_stale_sec', default_value='3.0'),
        DeclareLaunchArgument('contact_recovery_enabled', default_value='true'),
        DeclareLaunchArgument('contact_cmd_speed_min', default_value='0.025'),
        DeclareLaunchArgument('contact_odom_speed_max', default_value='0.012'),
        DeclareLaunchArgument('contact_odom_angular_max', default_value='0.08'),
        DeclareLaunchArgument('contact_stall_sec', default_value='0.55'),
        DeclareLaunchArgument('contact_recovery_cooldown_sec', default_value='1.8'),
        DeclareLaunchArgument('contact_odom_stale_sec', default_value='0.5'),
        DeclareLaunchArgument('tilt_recovery_enabled', default_value='true'),
        DeclareLaunchArgument('tilt_backup_deg', default_value='8.0'),
        DeclareLaunchArgument('tilt_stop_deg', default_value='18.0'),
        DeclareLaunchArgument('tilt_imu_stale_sec', default_value='0.6'),
        DeclareLaunchArgument('debug_decisions', default_value='true'),
        DeclareLaunchArgument('use_nav2_collision_monitor', default_value='false'),
    ]

    project_c_direct = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(project_c_launch),
        condition=UnlessCondition(LaunchConfiguration('use_nav2_collision_monitor')),
        launch_arguments={
            'scan_topic': LaunchConfiguration('scan_topic'),
            'depth_topic': LaunchConfiguration('depth_topic'),
            'pointcloud_topic': LaunchConfiguration('pointcloud_topic'),
            'pointcloud_frame': LaunchConfiguration('pointcloud_frame'),
            'pointcloud_target_frame': LaunchConfiguration('pointcloud_target_frame'),
            'pointcloud_use_tf': LaunchConfiguration('pointcloud_use_tf'),
            'pointcloud_tf_timeout_sec': LaunchConfiguration('pointcloud_tf_timeout_sec'),
            'pointcloud_qos': LaunchConfiguration('pointcloud_qos'),
            'tof_topic': LaunchConfiguration('tof_topic'),
            'tof_topics': LaunchConfiguration('tof_topics'),
            'use_lidar': LaunchConfiguration('use_lidar'),
            'use_depth': LaunchConfiguration('use_depth'),
            'use_pointcloud': LaunchConfiguration('use_pointcloud'),
            'use_tof': LaunchConfiguration('use_tof'),
            'front_center_angle_deg': LaunchConfiguration('front_center_angle_deg'),
            'front_path_half_width_m': LaunchConfiguration('front_path_half_width_m'),
            'cmd_vel_topic': LaunchConfiguration('cmd_vel_topic'),
            'cmd_vel_stamped': LaunchConfiguration('cmd_vel_stamped'),
            'odom_topic': LaunchConfiguration('odom_topic'),
            'imu_topic': LaunchConfiguration('imu_topic'),
            'front_tof_topics': LaunchConfiguration('front_tof_topics'),
            'max_speed': LaunchConfiguration('max_speed'),
            'stop_distance': LaunchConfiguration('stop_distance'),
            'hard_backup_distance': LaunchConfiguration('hard_backup_distance'),
            'front_tof_obstacle_distance': LaunchConfiguration('front_tof_obstacle_distance'),
            'front_tof_hard_distance': LaunchConfiguration('front_tof_hard_distance'),
            'dodge_clearance': LaunchConfiguration('dodge_clearance'),
            'dodge_forward_speed': LaunchConfiguration('dodge_forward_speed'),
            'dodge_angular_speed': LaunchConfiguration('dodge_angular_speed'),
            'rotation_angular_speed': LaunchConfiguration('rotation_angular_speed'),
            'dodge_step_deg': LaunchConfiguration('dodge_step_deg'),
            'dodge_pivot_sec': LaunchConfiguration('dodge_pivot_sec'),
            'front_release_distance': LaunchConfiguration('front_release_distance'),
            'front_clear_exit_frames': LaunchConfiguration('front_clear_exit_frames'),
            'creep_speed': LaunchConfiguration('creep_speed'),
            'clearer_side_deadband': LaunchConfiguration('clearer_side_deadband'),
            'avoid_turn_direction': LaunchConfiguration('avoid_turn_direction'),
            'side_guard_distance': LaunchConfiguration('side_guard_distance'),
            'side_escape_distance': LaunchConfiguration('side_escape_distance'),
            'side_escape_angular_speed': LaunchConfiguration('side_escape_angular_speed'),
            'edge_escape_enabled': LaunchConfiguration('edge_escape_enabled'),
            'edge_escape_front_distance': LaunchConfiguration('edge_escape_front_distance'),
            'edge_escape_clearance': LaunchConfiguration('edge_escape_clearance'),
            'edge_escape_angular_speed': LaunchConfiguration('edge_escape_angular_speed'),
            'edge_escape_sec': LaunchConfiguration('edge_escape_sec'),
            'edge_escape_max_attempts': LaunchConfiguration('edge_escape_max_attempts'),
            'backup_speed': LaunchConfiguration('backup_speed'),
            'battery_topic': LaunchConfiguration('battery_topic'),
            'require_battery_ok': LaunchConfiguration('require_battery_ok'),
            'min_battery_voltage': LaunchConfiguration('min_battery_voltage'),
            'warn_battery_voltage': LaunchConfiguration('warn_battery_voltage'),
            'battery_stale_sec': LaunchConfiguration('battery_stale_sec'),
            'contact_recovery_enabled': LaunchConfiguration('contact_recovery_enabled'),
            'contact_cmd_speed_min': LaunchConfiguration('contact_cmd_speed_min'),
            'contact_odom_speed_max': LaunchConfiguration('contact_odom_speed_max'),
            'contact_odom_angular_max': LaunchConfiguration('contact_odom_angular_max'),
            'contact_stall_sec': LaunchConfiguration('contact_stall_sec'),
            'contact_recovery_cooldown_sec': LaunchConfiguration('contact_recovery_cooldown_sec'),
            'contact_odom_stale_sec': LaunchConfiguration('contact_odom_stale_sec'),
            'tilt_recovery_enabled': LaunchConfiguration('tilt_recovery_enabled'),
            'tilt_backup_deg': LaunchConfiguration('tilt_backup_deg'),
            'tilt_stop_deg': LaunchConfiguration('tilt_stop_deg'),
            'tilt_imu_stale_sec': LaunchConfiguration('tilt_imu_stale_sec'),
            'debug_decisions': LaunchConfiguration('debug_decisions'),
        }.items(),
    )

    project_c_raw = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(project_c_launch),
        condition=IfCondition(LaunchConfiguration('use_nav2_collision_monitor')),
        launch_arguments={
            'scan_topic': LaunchConfiguration('scan_topic'),
            'depth_topic': LaunchConfiguration('depth_topic'),
            'pointcloud_topic': LaunchConfiguration('pointcloud_topic'),
            'pointcloud_frame': LaunchConfiguration('pointcloud_frame'),
            'pointcloud_target_frame': LaunchConfiguration('pointcloud_target_frame'),
            'pointcloud_use_tf': LaunchConfiguration('pointcloud_use_tf'),
            'pointcloud_tf_timeout_sec': LaunchConfiguration('pointcloud_tf_timeout_sec'),
            'pointcloud_qos': LaunchConfiguration('pointcloud_qos'),
            'tof_topic': LaunchConfiguration('tof_topic'),
            'tof_topics': LaunchConfiguration('tof_topics'),
            'use_lidar': LaunchConfiguration('use_lidar'),
            'use_depth': LaunchConfiguration('use_depth'),
            'use_pointcloud': LaunchConfiguration('use_pointcloud'),
            'use_tof': LaunchConfiguration('use_tof'),
            'front_center_angle_deg': LaunchConfiguration('front_center_angle_deg'),
            'front_path_half_width_m': LaunchConfiguration('front_path_half_width_m'),
            'cmd_vel_topic': LaunchConfiguration('cmd_vel_raw_topic'),
            'cmd_vel_stamped': LaunchConfiguration('cmd_vel_stamped'),
            'odom_topic': LaunchConfiguration('odom_topic'),
            'imu_topic': LaunchConfiguration('imu_topic'),
            'front_tof_topics': LaunchConfiguration('front_tof_topics'),
            'max_speed': LaunchConfiguration('max_speed'),
            'stop_distance': LaunchConfiguration('stop_distance'),
            'hard_backup_distance': LaunchConfiguration('hard_backup_distance'),
            'front_tof_obstacle_distance': LaunchConfiguration('front_tof_obstacle_distance'),
            'front_tof_hard_distance': LaunchConfiguration('front_tof_hard_distance'),
            'dodge_clearance': LaunchConfiguration('dodge_clearance'),
            'dodge_forward_speed': LaunchConfiguration('dodge_forward_speed'),
            'dodge_angular_speed': LaunchConfiguration('dodge_angular_speed'),
            'rotation_angular_speed': LaunchConfiguration('rotation_angular_speed'),
            'dodge_step_deg': LaunchConfiguration('dodge_step_deg'),
            'dodge_pivot_sec': LaunchConfiguration('dodge_pivot_sec'),
            'front_release_distance': LaunchConfiguration('front_release_distance'),
            'front_clear_exit_frames': LaunchConfiguration('front_clear_exit_frames'),
            'creep_speed': LaunchConfiguration('creep_speed'),
            'clearer_side_deadband': LaunchConfiguration('clearer_side_deadband'),
            'avoid_turn_direction': LaunchConfiguration('avoid_turn_direction'),
            'side_guard_distance': LaunchConfiguration('side_guard_distance'),
            'side_escape_distance': LaunchConfiguration('side_escape_distance'),
            'side_escape_angular_speed': LaunchConfiguration('side_escape_angular_speed'),
            'edge_escape_enabled': LaunchConfiguration('edge_escape_enabled'),
            'edge_escape_front_distance': LaunchConfiguration('edge_escape_front_distance'),
            'edge_escape_clearance': LaunchConfiguration('edge_escape_clearance'),
            'edge_escape_angular_speed': LaunchConfiguration('edge_escape_angular_speed'),
            'edge_escape_sec': LaunchConfiguration('edge_escape_sec'),
            'edge_escape_max_attempts': LaunchConfiguration('edge_escape_max_attempts'),
            'backup_speed': LaunchConfiguration('backup_speed'),
            'battery_topic': LaunchConfiguration('battery_topic'),
            'require_battery_ok': LaunchConfiguration('require_battery_ok'),
            'min_battery_voltage': LaunchConfiguration('min_battery_voltage'),
            'warn_battery_voltage': LaunchConfiguration('warn_battery_voltage'),
            'battery_stale_sec': LaunchConfiguration('battery_stale_sec'),
            'contact_recovery_enabled': LaunchConfiguration('contact_recovery_enabled'),
            'contact_cmd_speed_min': LaunchConfiguration('contact_cmd_speed_min'),
            'contact_odom_speed_max': LaunchConfiguration('contact_odom_speed_max'),
            'contact_odom_angular_max': LaunchConfiguration('contact_odom_angular_max'),
            'contact_stall_sec': LaunchConfiguration('contact_stall_sec'),
            'contact_recovery_cooldown_sec': LaunchConfiguration('contact_recovery_cooldown_sec'),
            'contact_odom_stale_sec': LaunchConfiguration('contact_odom_stale_sec'),
            'tilt_recovery_enabled': LaunchConfiguration('tilt_recovery_enabled'),
            'tilt_backup_deg': LaunchConfiguration('tilt_backup_deg'),
            'tilt_stop_deg': LaunchConfiguration('tilt_stop_deg'),
            'tilt_imu_stale_sec': LaunchConfiguration('tilt_imu_stale_sec'),
            'debug_decisions': LaunchConfiguration('debug_decisions'),
        }.items(),
    )

    collision_monitor = Node(
        package='nav2_collision_monitor',
        executable='collision_monitor',
        name='collision_monitor',
        condition=IfCondition(LaunchConfiguration('use_nav2_collision_monitor')),
        output='screen',
        parameters=[
            collision_config,
            {
                'cmd_vel_in_topic': LaunchConfiguration('cmd_vel_raw_topic'),
                'cmd_vel_out_topic': LaunchConfiguration('cmd_vel_topic'),
                'scan.topic': LaunchConfiguration('scan_topic'),
                'pointcloud.topic': LaunchConfiguration('pointcloud_topic'),
            },
        ],
    )

    lifecycle_manager = Node(
        package='nav2_lifecycle_manager',
        executable='lifecycle_manager',
        name='lifecycle_manager_collision_monitor',
        condition=IfCondition(LaunchConfiguration('use_nav2_collision_monitor')),
        output='screen',
        parameters=[
            {
                'autostart': True,
                'node_names': ['collision_monitor'],
            }
        ],
    )

    return LaunchDescription(args + [
        project_c_direct,
        project_c_raw,
        collision_monitor,
        lifecycle_manager,
    ])
